# Generated by Django 6.1 on 2026-10-03 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='banner_image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
