# Generated by Django 6.0.8 on 2026-10-03 03:23

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_promotion_banner_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='discount_type',
            field=models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='percentage', max_length=20),
        ),
        migrations.AddField(
            model_name='promotion',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='banner_image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
