"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.1.
"""

from pathlib import Path
import os
import sys
import warnings
import dj_database_url
from dotenv import load_dotenv
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-j@%g_#f_!=@e#9&vm0z-j(b_a9*m_8&7yzegz&mz0brkxx3qy$')

DEBUG = os.getenv('DEBUG', 'False').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')

# Google OAuth Credentials
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '968981357423-os92276mmfmdfv1diteradinnvogd2q5.apps.googleusercontent.com')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')

# Frontend URL — used to build verification links in emails.
# Set FRONTEND_URL in .env for each environment.
FRONTEND_URL = os.getenv('FRONTEND_URL', 'http://localhost:5173').rstrip('/')

# How long (seconds) an email verification token stays valid. Default = 24 hours.
VERIFICATION_TOKEN_EXPIRY_SECONDS = int(os.getenv('VERIFICATION_TOKEN_EXPIRY_SECONDS', 86400))

# Bakong PayWay / KHQR credentials (kept server-side, never sent to the browser).
BAKONG_MERCHANT_ID = os.getenv('BAKONG_MERCHANT_ID', 'ly_sokheng1@bkrt')
BAKONG_MERCHANT_NAME = os.getenv('BAKONG_MERCHANT_NAME', 'SOKHENG LY')
BAKONG_MERCHANT_CITY = os.getenv('BAKONG_MERCHANT_CITY', 'PHNOM PENH')
# Sandbox (testing only): https://sit-api-bakong.nbc.gov.kh
# Production (real payments): https://api-bakong.nbc.gov.kh
# Default to PRODUCTION so payments made through the real Bakong app are
# actually verified. Only switch to the SIT sandbox for non-live testing.
BAKONG_BASE_URL = os.getenv('BAKONG_BASE_URL', 'https://api-bakong.nbc.gov.kh')

# JWT token from the NBC developer portal (expires ~30 days).
# Visit https://api-bakong.nbc.gov.kh/register/ -> Login -> Get Token.
# When expired/rejected, the backend will auto-renew via POST /v1/renew_token
# using BAKONG_EMAIL (if set). Missing token causes AUTH_CONFIG_ERROR responses.
BAKONG_TOKEN = os.getenv('BAKONG_TOKEN', '')

# Registered email address for the Bakong developer account.
# Required for automatic token renewal via POST /v1/renew_token.
BAKONG_EMAIL = os.getenv('BAKONG_EMAIL', '')

# ---------------------------------------------------------------------------
# Startup alert for Bakong auth configuration. Runs once at process startup so
# operators notice a missing/expired token immediately. Never logs the token.
# ---------------------------------------------------------------------------
if not BAKONG_TOKEN:
    warnings.warn(
        'Bakong auth config error: BAKONG_TOKEN is missing/empty. Set the '
        'BAKONG_TOKEN environment variable in the deployment environment '
        '(Vercel project settings or Backend/.env) or payment verification '
        'will return AUTH_CONFIG_ERROR.',
        stacklevel=2,
    )
else:
    try:
        import base64
        import json as _json

        _payload = _json.loads(base64.urlsafe_b64decode(BAKONG_TOKEN.split('.')[1] + '=='))
        _exp = _payload.get('exp') if isinstance(_payload, dict) else None
        if _exp:
            import time as _time
            _remaining = int(_exp) - _time.time()
            if _remaining <= 0:
                warnings.warn(
                    'Bakong auth config error: BAKONG_TOKEN has EXPIRED. '
                    'Generate a new token from the NBC developer portal and '
                    'update the deployment environment.',
                    stacklevel=2,
                )
            elif _remaining < 7 * 86400:
                warnings.warn(
                    f'Bakong auth config warning: BAKONG_TOKEN expires in '
                    f'~{int(_remaining // 86400)} day(s). Renew it before it '
                    f'lapses or payment verification will break.',
                    stacklevel=2,
                )
    except Exception:
        # Token is not a decodable JWT; bakong.py validates on each call.
        pass


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'corsheaders',
    'rest_framework',
    
    # Local apps
    'accounts',
    'catalog',
    'stock',
    'shopping',
    'orders',
    'marketing',
    'notifications',
    'payments',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # Must stay at the very top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(
        default=os.getenv(
            'DATABASE_URL',
            f"postgresql://{os.getenv('DB_USER', 'postgres')}:{os.getenv('DB_PASSWORD', 'SH0972380788@')}@{os.getenv('DB_HOST', 'localhost')}:{os.getenv('DB_PORT', '5432')}/{os.getenv('DB_NAME', 'Protech.')}"
        ),
        conn_max_age=600,
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Custom User Model
AUTH_USER_MODEL = 'accounts.User'


# Internationalization
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploads, promo banners, product images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# File and Data Upload Limits (Allow wide high-res promo banner uploads up to 50MB)
DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 50 MB

# Email Configuration
# Development (DEBUG=True) defaults to the console backend, which prints emails
# to the terminal instead of sending them. Production (DEBUG=False) defaults to
# the real SMTP backend. Set EMAIL_BACKEND explicitly to force a specific backend.
if os.getenv('EMAIL_BACKEND'):
    EMAIL_BACKEND = os.getenv('EMAIL_BACKEND')
elif DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() in ('true', '1')
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False').lower() in ('true', '1')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# Gmail/other SMTP providers reject emails whose From address is not the
# authenticated account, so default the From address to the SMTP login.
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER or 'Protech <noreply@protech.com>')


# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
    "https://protech-tau-sepia.vercel.app",
    "https://protech-2s0ekwa6n-sokheng-s-projects.vercel.app",
    "https://protech-dy5.pages.dev",
    "https://17b35fba.protech-dy5.pages.dev"
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.pages\.dev$",
    r"^https://.*\.vercel\.app$",
    r"^https://.*\.loca\.lt$",
    r"^https://.*\.ngrok-free\.app$",
    r"^https://.*\.ngrok-free\.dev$",
    r"^https://.*\.trycloudflare\.com$",
]

CSRF_TRUSTED_ORIGINS = [
    "https://protech-dy5.pages.dev",
    "https://*.pages.dev",
    "https://*.trycloudflare.com",
]

CORS_ALLOW_HEADERS = list(default_headers) + [
    'bypass-tunnel-reminder',
    'ngrok-skip-browser-warning',
    'x-session-id',
]

CORS_ALLOW_CREDENTIALS = True

# ---------------------------------------------------------------------------
# Logging — make sure payment/Bakong diagnostics (including full stack traces)
# reach the server console/log stream. On Vercel, stderr is captured as the
# log stream; a file handler is only added when BAKONG_LOG_FILE is explicitly
# set (the serverless filesystem is read-only by default).
# ---------------------------------------------------------------------------
_BAKONG_LOG_FILE = os.getenv('BAKONG_LOG_FILE', '')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}:{lineno} {message} {exc_info}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'payments': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}
if _BAKONG_LOG_FILE:
    _log_dir = os.path.dirname(_BAKONG_LOG_FILE)
    if _log_dir and not os.path.isdir(_log_dir):
        try:
            os.makedirs(_log_dir)
        except OSError:
            _BAKONG_LOG_FILE = ''
    if _BAKONG_LOG_FILE:
        LOGGING['handlers']['bakong_file'] = {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': _BAKONG_LOG_FILE,
            'maxBytes': 10 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        }
        LOGGING['loggers']['payments']['handlers'].append('bakong_file')


# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '1000/day',
        'user': '10000/day',
        'auth': '30/minute',
    },
    'EXCEPTION_HANDLER': 'core.exceptions.custom_exception_handler',
    'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema' if 'rest_framework.schemas.coreapi' in sys.modules else 'rest_framework.schemas.openapi.AutoSchema',
}

# JWT Token Configuration
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': False,
    'AUTH_HEADER_TYPES': ('Bearer',),
}