# Generated by Django 6.1 on 2026-08-22 08:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_product_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecificationOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('definition', models.ForeignKey(db_column='definition_id', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='catalog.specificationdefinition')),
            ],
            options={
                'db_table': 'specification_options',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
