# Generated by Django 6.0.8 on 2026-10-03 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_base_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('KHR', 'KHR')], default='USD', max_length=10),
        ),
    ]
