# Generated by Django 6.1 on 2026-08-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('bakong_khqr', 'Bakong KHQR')], default='bakong_khqr', max_length=50),
        ),
    ]
