# Generated by Django 6.1 on 2026-08-19 17:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='Orders with a subtotal at or above this amount ship free.', max_digits=12)),
                ('flat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Flat shipping rate charged on orders below the free-shipping threshold.', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shipping settings',
                'verbose_name_plural': 'Shipping settings',
                'db_table': 'shipping_config',
            },
        ),
    ]
