import React, { useState, useEffect, useCallback } from "react";
import { useSearchParams, useNavigate, Link } from "react-router-dom";
import { getOrderDetailApi, generateKhqrApi, getGuestEmail } from "../../services/api";
import { formatMoney, formatStatusBadge, paymentStatusStyle } from "../../utils/format";
import KhqrPaymentModal from "../../components/payment/KhqrPaymentModal";
import bakongLogo from "../../assets/image.png"

const PaymentPage = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const orderId = searchParams.get("order");

  const [order, setOrder] = useState(null);
  const [isLoading, setIsLoading] = useState(true);
  const [error, setError] = useState(null);

  const [khqr, setKhqr] = useState(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [generateError, setGenerateError] = useState(null);
  const [autoGenerated, setAutoGenerated] = useState(false);

  const loadOrder = useCallback(() => {
    if (!orderId) {
      setError("No order found to pay for.");
      setIsLoading(false);
      return;
    }
    getOrderDetailApi(orderId)
      .then((res) => setOrder(res.data))
      .catch(() => setError("Order not found."))
      .finally(() => setIsLoading(false));
  }, [orderId]);

  useEffect(() => {
    loadOrder();
  }, [loadOrder]);

  const generateQr = useCallback(async () => {
    if (!orderId) return;
    setIsGenerating(true);
    setGenerateError(null);
    try {
      const payload = {};
      const guestEmail = getGuestEmail();
      if (guestEmail) payload.guest_email = guestEmail;
      const res = await generateKhqrApi(orderId, payload);
      console.log("[DEBUG PaymentPage] generateKhqr response:", res.data);
      setKhqr({
        qr: res.data.qr,
        md5: res.data.md5,
        deepLink: res.data.deep_link,
        deep_link: res.data.deep_link,
        deeplink: res.data.deep_link,
        ...res.data,
      });
    } catch (err) {
      setGenerateError(err.response?.data?.error || "Failed to generate Bakong QR code.");
    } finally {
      setIsGenerating(false);
    }
  }, [orderId]);

  // Auto-open the Bakong KHQR modal right after the order is loaded.
  useEffect(() => {
    if (order && order.payment_status !== "paid" && !autoGenerated && !isGenerating) {
      setAutoGenerated(true);
      generateQr();
    }
  }, [order, autoGenerated, isGenerating, generateQr]);

  const handlePaid = useCallback(
    (paidOrder) => {
      setOrder(paidOrder || null);
      const successId = paidOrder?.id || orderId;
      navigate(`/checkout/success?order=${successId}`);
    },
    [navigate, orderId]
  );

  const handleCloseModal = () => {
    setKhqr(null);
  };

  if (isLoading) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-20 text-center">
        <div className="w-12 h-12 border-4 border-sky-500/20 border-t-sky-500 rounded-full animate-spin mx-auto mb-4" />
        <p className="text-gray-500 text-sm animate-pulse">Preparing payment...</p>
      </div>
    );
  }

  if (error || !order) {
    return (
      <div className="max-w-4xl mx-auto px-4 py-20 text-center">
        <div className="w-16 h-16 bg-orange-50 text-primary rounded-full flex items-center justify-center mx-auto text-3xl mb-4">
          <i className="bi bi-exclamation-octagon" />
        </div>
        <h2 className="text-xl font-bold text-gray-900">{error || "Payment Unavailable"}</h2>
        <Link
          to="/cart"
          className="inline-block mt-4 px-6 py-2.5 rounded-xl bg-button hover:bg-button-hover text-white font-bold text-xs"
        >
          Back to Cart
        </Link>
      </div>
    );
  }

  const isPaid = order.payment_status === "paid";

  return (
    <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
      {/* Steps indicator */}
      <div className="flex items-center justify-center gap-2 sm:gap-4 mb-8 text-xs font-bold">
        <span className="flex items-center gap-1.5 text-emerald-600">
          <span className="w-6 h-6 rounded-full bg-emerald-500 text-white flex items-center justify-center">
            <i className="bi bi-check text-sm" />
          </span>
          Shipping
        </span>
        <i className="bi bi-chevron-right text-gray-300" />
        <span className="flex items-center gap-1.5 text-sky-600">
          <span className="w-6 h-6 rounded-full bg-sky-500 text-white flex items-center justify-center">2</span>
          Payment
        </span>
        <i className="bi bi-chevron-right text-gray-300" />
        <span className="flex items-center gap-1.5 text-gray-400">
          <span className="w-6 h-6 rounded-full bg-gray-200 text-gray-500 flex items-center justify-center">3</span>
          Confirm
        </span>
      </div>

      <h1 className="text-2xl sm:text-3xl font-black text-gray-900 tracking-tight mb-2">
        Payment
      </h1>
      <p className="text-xs text-gray-500 mb-8">
        Order{" "}
        <Link to={`/orders/${order.id}`} className="text-sky-600 font-semibold hover:underline">
          {order.order_number}
        </Link>{" "}
        · {formatMoney(order.total, order.currency)}
      </p>

      {isPaid ? (
        <div className="bg-white rounded-3xl p-12 text-center border border-gray-100 shadow-sm">
          <div className="w-16 h-16 mx-auto rounded-full bg-emerald-50 flex items-center justify-center mb-4">
            <i className="bi bi-check-circle text-3xl text-emerald-500" />
          </div>
          <h2 className="text-xl font-bold text-gray-900 mb-2">Order already paid</h2>
          <p className="text-sm text-gray-500 mb-6">
            {formatStatusBadge(order.payment_status, paymentStatusStyle)} payment recorded for this
            order.
          </p>
          <Link
            to={`/orders/${order.id}/success`}
            className="inline-flex items-center gap-2 px-6 py-3 rounded-2xl bg-button hover:bg-button-hover text-white font-bold text-sm shadow-md"
          >
            <i className="bi bi-check2-circle" />
            View Confirmation
          </Link>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-start">
          {/* Bakong KHQR Panel */}
          <div className="bg-white rounded-3xl p-6 sm:p-8 border border-gray-100 shadow-sm">
            <div className="flex items-center gap-3 mb-6">
              <img src={bakongLogo} alt="Bakong" className="w-12 h-12 object-contain rounded-2xl" />
              <div>
                <h2 className="text-base font-bold text-gray-900">Bakong KHQR</h2>
                <p className="text-[11px] text-gray-400">
                  Scan the QR code with the Bakong app to complete your payment.
                </p>
              </div>
            </div>

            {isGenerating ? (
              <div className="py-16 text-center">
                <div className="w-12 h-12 border-4 border-sky-500/20 border-t-sky-500 rounded-full animate-spin mx-auto mb-4" />
                <p className="text-xs text-gray-500 animate-pulse">Generating Bakong QR code...</p>
              </div>
            ) : (
              <>
                <button
                  type="button"
                  onClick={generateQr}
                  className="w-full py-4 rounded-2xl bg-button hover:bg-button-hover text-white font-bold text-sm shadow-md hover:shadow-lg transition-all flex items-center justify-center gap-2 cursor-pointer"
                >
                  <i className="bi bi-qr-code-scan" />
                  {khqr ? "Show QR Code Again" : `Generate QR & Pay ${formatMoney(order.total, order.currency)}`}
                </button>

                {generateError && (
                  <div className="mt-4 p-3 rounded-2xl bg-orange-50 border border-orange-200 text-primary text-xs flex items-center gap-2">
                    <i className="bi bi-exclamation-triangle-fill text-primary" />
                    <span>{generateError}</span>
                  </div>
                )}

                {khqr && !generateError && (
                  <div className="mt-4 p-3 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs flex items-center gap-2">
                    <i className="bi bi-check-circle-fill text-emerald-500" />
                    <span>QR code ready. The payment modal will open automatically.</span>
                  </div>
                )}
              </>
            )}
          </div>

          {/* Order Summary */}
          <div className="bg-white rounded-3xl p-6 border border-gray-100 shadow-sm">
            <h3 className="text-sm font-bold text-gray-900 mb-4">Payment Summary</h3>
            <div className="space-y-3 max-h-56 overflow-y-auto pr-1 mb-4">
              {order.items?.map((item) => (
                <div key={item.id} className="flex items-center gap-3">
                  <div className="w-12 h-12 shrink-0 bg-slate-50 rounded-xl border border-gray-100 flex items-center justify-center text-gray-300">
                    <i className="bi bi-box text-lg" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-xs font-bold text-gray-900 line-clamp-1">
                      {item.product_name_snapshot}
                    </p>
                    <p className="text-[11px] text-gray-500">
                      {item.sku_snapshot} × {item.quantity}
                    </p>
                  </div>
                  <span className="text-xs font-bold text-gray-900">
                    {formatMoney(item.total, order.currency)}
                  </span>
                </div>
              ))}
            </div>

            <div className="space-y-2.5 text-sm border-t border-gray-100 pt-4">
              <div className="flex items-center justify-between text-gray-600">
                <span>Subtotal</span>
                <span className="font-semibold text-gray-900">{formatMoney(order.subtotal, order.currency)}</span>
              </div>
              {Number(order.discount) > 0 && (
                <div className="flex items-center justify-between text-emerald-600">
                  <span>Discount</span>
                  <span className="font-semibold">-{formatMoney(order.discount, order.currency)}</span>
                </div>
              )}
              <div className="flex items-center justify-between text-gray-600">
                <span>Shipping</span>
                <span className="font-semibold text-gray-900">
                  {Number(order.shipping_cost) === 0 ? (
                    <span className="text-emerald-600">Free</span>
                  ) : (
                    formatMoney(order.shipping_cost, order.currency)
                  )}
                </span>
              </div>
              <div className="flex items-center justify-between text-gray-600">
                <span>Tax</span>
                <span className="font-semibold text-gray-900">{formatMoney(order.tax, order.currency)}</span>
              </div>
            </div>

            <div className="mt-4 pt-4 border-t border-gray-100 flex items-center justify-between">
              <span className="text-sm font-bold text-gray-900">Total Due</span>
              <span className="text-xl font-black text-gray-900 tracking-tight">
                {formatMoney(order.total, order.currency)}
              </span>
            </div>

            <Link
              to="/cart"
              className="mt-4 w-full py-2.5 rounded-2xl border border-gray-200 hover:border-sky-300 hover:bg-sky-50 text-gray-600 hover:text-sky-700 text-sm font-semibold transition-colors flex items-center justify-center gap-2"
            >
              <i className="bi bi-arrow-left" />
              Back to Cart
            </Link>
          </div>
        </div>
      )}

      {/* Bakong KHQR payment modal */}
      {khqr && khqr.qr && !isPaid && (
        <KhqrPaymentModal
          order={order}
          qrPayload={khqr.qr}
          deepLink={khqr.deepLink}
          paymentData={khqr}
          md5={khqr.md5}
          onPaid={handlePaid}
          onClose={handleCloseModal}
        />
      )}
    </div>
  );
};

export default PaymentPage;