# Generated by Django 6.0.8 on 2026-10-02 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_variant_specifications'),
        ('shopping', '0002_wishlist_wishlist_user_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlistitem',
            name='variant',
            field=models.ForeignKey(blank=True, db_column='variant_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_items', to='catalog.productvariant'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlistitem',
            unique_together={('wishlist', 'product', 'variant')},
        ),
        migrations.AddIndex(
            model_name='wishlistitem',
            index=models.Index(fields=['wishlist', 'variant'], name='wishlist_item_variant_idx'),
        ),
    ]
